### ISSUE TITLE
Fix marriage "your marriage will end if you don't have enough sonhos" message causing global rate limits

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2142]
The message is causing some very bad global rate limits, also it seems the marriage is never deleted even if it should

**Comment by MrPowerGamerBR** [comment]
```
[19:00:10.833] [DailyTaxTask Executor Thread-0/WARN]: Transaction attempt #0 failed: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update. Statement(s): UPDATE profiles SET money=(profiles.money - ?) WHERE profiles.marriage IS NOT NULL AND profiles.money >= ?
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask$runDailyTax$7.invoke(DailyTaxTask.kt:218)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask$runDailyTax$7.invoke(DailyTaxTask.kt:24)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask.runDailyTax(DailyTaxTask.kt:217)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask.run(DailyTaxTask.kt:32)
[19:00:11.191] [DailyTaxTask Executor Thread-0/WARN]: Transaction attempt #1 failed: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update. Statement(s): UPDATE profiles SET money=(profiles.money - ?) WHERE profiles.marriage IS NOT NULL AND profiles.money >= ?
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask$runDailyTax$7.invoke(DailyTaxTask.kt:218)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask$runDailyTax$7.invoke(DailyTaxTask.kt:24)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask.runDailyTax(DailyTaxTask.kt:217)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask.run(DailyTaxTask.kt:32)
[19:00:11.757] [DailyTaxTask Executor Thread-0/WARN]: Transaction attempt #2 failed: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update. Statement(s): UPDATE profiles SET money=(profiles.money - ?) WHERE profiles.marriage IS NOT NULL AND profiles.money >= ?
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask$runDailyTax$7.invoke(DailyTaxTask.kt:218)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask$runDailyTax$7.invoke(DailyTaxTask.kt:24)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask.runDailyTax(DailyTaxTask.kt:217)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask.run(DailyTaxTask.kt:32)
[19:00:11.758] [DailyTaxTask Executor Thread-0/ERROR]: Erro ao atualizar a taxa diária!
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask$runDailyTax$7.invoke(DailyTaxTask.kt:218)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask$runDailyTax$7.invoke(DailyTaxTask.kt:24)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask.runDailyTax(DailyTaxTask.kt:217)
        at com.mrpowergamerbr.loritta.utils.DailyTaxTask.run(DailyTaxTask.kt:32)
```
