### ISSUE TITLE
Bug on init Loritta with SqLite

### ISSUE THREAD

**Issue by yStreakBR** [LorittaBot/Loritta#2500]
Exception in thread "main" java.sql.SQLException: SQLite supports only TRANSACTION_SERIALIZABLE and TRANSACTION_READ_UNCOMMITTED.
        at org.sqlite.SQLiteConnection.setTransactionIsolation(SQLiteConnection.java:164)
        at com.zaxxer.hikari.pool.ProxyConnection.setTransactionIsolation(ProxyConnection.java:433)
        at com.zaxxer.hikari.pool.HikariProxyConnection.setTransactionIsolation(HikariProxyConnection.java)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.setTransactionIsolation(JdbcConnectionImpl.kt:46)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:71)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:68)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:75)
        at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
        at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:39)
        at org.jetbrains.exposed.sql.Database$identifierManager$2.invoke(Database.kt:59)
        at org.jetbrains.exposed.sql.Database$identifierManager$2.invoke(Database.kt:59)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.exposed.sql.Database.getIdentifierManager(Database.kt:59)
        at org.jetbrains.exposed.sql.Transaction.identity(Transaction.kt:185)
        at pw.forst.exposed.InsertOrUpdate$prepareSQL$updateSetter$1.invoke(InsertOrUpdate.kt:20)
        at pw.forst.exposed.InsertOrUpdate$prepareSQL$updateSetter$1.invoke(InsertOrUpdate.kt:20)
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3347)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3364)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3363)
        at pw.forst.exposed.InsertOrUpdate.prepareSQL(InsertOrUpdate.kt:20)
        at org.jetbrains.exposed.sql.statements.StatementContext.sql(Statement.kt:74)
        at org.jetbrains.exposed.sql.statements.StatementKt.expandArgs(Statement.kt:78)
        at org.jetbrains.exposed.sql.Slf4jSqlDebugLogger.log(SQLLog.kt:32)
        at org.jetbrains.exposed.sql.CompositeSqlLogger.log(SQLLog.kt:50)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.handleSQLException(ThreadLocalTransactionManager.kt:235)
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:131)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by MrPowerGamerBR** [comment]
> You can also host Loritta yourself, however we won't give support for people that are trying to selfhost her, we don't want to spend hours trying to troubleshoot other people issues that only happens on selfhosted instances, so you should at least know how to troubleshoot issues, if you find any.

If you really want to, use PostgreSQL, not SQLite.

**Comment by yStreakBR** [comment]
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "profiledesigngroupentries" violates foreign key constraint "fk_profiledesigngroupentries_profile_design_internal_name"
  Detail: Key (profile_design)=(defaultBlurple) is not present in table "profiledesigns".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:26)
        at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:118)
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:126)
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:60)
        ... 17 more

with PostgreSQL
