### ISSUE TITLE
Cinnamon exited with code 1

### ISSUE THREAD

**Issue by bloodieee** [LorittaBot/Loritta#2657]
2024-07-19 13:21:14 cinnamon-1               | WARNING: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent3413798516442188700.jar)
2024-07-19 13:21:14 cinnamon-1               | WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
2024-07-19 13:21:14 cinnamon-1               | WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
2024-07-19 13:21:14 cinnamon-1               | WARNING: Dynamic loading of agents will be disallowed by default in a future release
2024-07-19 13:22:31 cinnamon-1               | Jul 19, 2024 5:22:29 AM com.fasterxml.jackson.databind.PropertyNamingStrategy$PropertyNamingStrategyBase <init>
2024-07-19 01:15:10 postgresql-1             | The files belonging to this database system will be owned by user "postgres".
2024-07-19 01:15:10 postgresql-1             | This user must also own the server process.
2024-07-19 01:15:10 postgresql-1             | 
2024-07-19 01:15:11 postgresql-1             | The database cluster will be initialized with locale "en_US.utf8".
2024-07-19 01:15:11 postgresql-1             | The default database encoding has accordingly been set to "UTF8".
2024-07-19 01:15:11 postgresql-1             | The default text search configuration will be set to "english".
2024-07-19 01:15:11 postgresql-1             | 
2024-07-19 01:15:11 postgresql-1             | Data page checksums are disabled.
2024-07-19 01:15:11 postgresql-1             | 
2024-07-19 01:15:11 postgresql-1             | fixing permissions on existing directory /var/lib/postgresql/data ... ok
2024-07-19 01:15:11 postgresql-1             | creating subdirectories ... ok
2024-07-19 01:15:11 postgresql-1             | selecting dynamic shared memory implementation ... posix
2024-07-19 01:15:15 postgresql-1             | selecting default max_connections ... 100
2024-07-19 01:15:15 postgresql-1             | selecting default shared_buffers ... 128MB
2024-07-19 01:15:16 postgresql-1             | selecting default time zone ... Etc/UTC
2024-07-19 01:15:16 postgresql-1             | creating configuration files ... ok
2024-07-19 01:15:18 postgresql-1             | running bootstrap script ... ok
2024-07-19 01:15:33 postgresql-1             | performing post-bootstrap initialization ... ok
2024-07-19 01:17:20 postgresql-1             | syncing data to disk ... 2024-07-19T05:18:26.269335653Z 
2024-07-19 13:18:26 postgresql-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-07-19 13:18:26 postgresql-1             | 
2024-07-19 13:19:05 postgresql-1             | 2024-07-19 05:19:05.571 UTC [1] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-07-19 13:19:05 postgresql-1             | 2024-07-19 05:19:05.936 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-19 13:19:05 postgresql-1             | 2024-07-19 05:19:05.936 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-07-19 13:19:08 postgresql-1             | 2024-07-19 05:19:08.147 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-19 13:19:11 postgresql-1             | 2024-07-19 05:19:11.336 UTC [29] LOG:  database system was shut down at 2024-07-18 17:15:33 UTC
2024-07-19 13:19:17 postgresql-1             | 2024-07-19 05:19:17.467 UTC [1] LOG:  database system is ready to accept connections
2024-07-19 13:24:11 postgresql-1             | 2024-07-19 05:24:11.419 UTC [27] LOG:  checkpoint starting: time
2024-07-19 13:24:14 postgresql-1             | 2024-07-19 05:24:14.124 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.620 s, sync=0.270 s, total=2.705 s; sync files=2, longest=0.136 s, average=0.135 s; distance=0 kB, estimate=0 kB; lsn=0/14E6A58, redo lsn=0/14E6A20
2024-07-19 13:35:55 postgresql-1             | 2024-07-19 05:35:55.320 UTC [1] LOG:  received fast shutdown request
2024-07-19 13:35:55 postgresql-1             | 2024-07-19 05:35:55.424 UTC [1] LOG:  aborting any active transactions
2024-07-19 13:35:55 postgresql-1             | 2024-07-19 05:35:55.426 UTC [1] LOG:  background worker "logical replication launcher" (PID 32) exited with exit code 1
2024-07-19 13:35:55 postgresql-1             | 2024-07-19 05:35:55.427 UTC [27] LOG:  shutting down
2024-07-19 13:35:55 postgresql-1             | 2024-07-19 05:35:55.524 UTC [27] LOG:  checkpoint starting: shutdown immediate
2024-07-19 13:35:55 postgresql-1             | 2024-07-19 05:35:55.780 UTC [27] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.353 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB; lsn=0/14E6B08, redo lsn=0/14E6B08
2024-07-19 13:35:55 postgresql-1             | 2024-07-19 05:35:55.787 UTC [1] LOG:  database system is shut down
2024-07-19 13:36:12 postgresql-1             | 
2024-07-19 13:36:12 postgresql-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-07-19 13:36:12 postgresql-1             | 
2024-07-19 13:36:13 postgresql-1             | 2024-07-19 05:36:13.827 UTC [1] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-07-19 13:36:13 postgresql-1             | 2024-07-19 05:36:13.827 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-19 13:36:13 postgresql-1             | 2024-07-19 05:36:13.827 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-07-19 13:36:14 postgresql-1             | 2024-07-19 05:36:14.147 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-19 13:36:14 postgresql-1             | 2024-07-19 05:36:14.438 UTC [29] LOG:  database system was shut down at 2024-07-19 05:35:55 UTC
2024-07-19 13:36:14 postgresql-1             | 2024-07-19 05:36:14.623 UTC [1] LOG:  database system is ready to accept connections
2024-07-19 13:39:41 postgresql-1             | 2024-07-19 05:39:41.312 UTC [1] LOG:  received fast shutdown request
2024-07-19 13:39:41 postgresql-1             | 2024-07-19 05:39:41.796 UTC [1] LOG:  aborting any active transactions
2024-07-19 13:39:41 postgresql-1             | 2024-07-19 05:39:41.798 UTC [1] LOG:  background worker "logical replication launcher" (PID 32) exited with exit code 1
2024-07-19 13:39:41 postgresql-1             | 2024-07-19 05:39:41.801 UTC [27] LOG:  shutting down
2024-07-19 13:39:42 postgresql-1             | 2024-07-19 05:39:42.218 UTC [27] LOG:  checkpoint starting: shutdown immediate
2024-07-19 13:39:46 postgresql-1             | 2024-07-19 05:39:46.750 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.332 s, sync=0.293 s, total=4.949 s; sync files=2, longest=0.205 s, average=0.147 s; distance=0 kB, estimate=0 kB; lsn=0/14E6BB8, redo lsn=0/14E6BB8
2024-07-19 13:39:46 postgresql-1             | 2024-07-19 05:39:46.757 UTC [1] LOG:  database system is shut down
2024-07-19 13:41:19 postgresql-1             | 
2024-07-19 13:41:19 postgresql-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-07-19 13:41:19 postgresql-1             | 
2024-07-19 13:41:20 postgresql-1             | 2024-07-19 05:41:20.287 UTC [1] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-07-19 13:41:20 postgresql-1             | 2024-07-19 05:41:20.287 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-19 13:41:20 postgresql-1             | 2024-07-19 05:41:20.287 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-07-19 13:41:20 postgresql-1             | 2024-07-19 05:41:20.866 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-19 13:41:21 postgresql-1             | 2024-07-19 05:41:21.518 UTC [28] LOG:  database system was shut down at 2024-07-19 05:39:46 UTC
2024-07-19 13:41:21 postgresql-1             | 2024-07-19 05:41:21.658 UTC [1] LOG:  database system is ready to accept connections
2024-07-19 13:42:32 postgresql-1             | 2024-07-19 05:42:32.818 UTC [1] LOG:  received fast shutdown request
2024-07-19 13:42:32 postgresql-1             | 2024-07-19 05:42:32.931 UTC [1] LOG:  aborting any active transactions
2024-07-19 13:42:32 postgresql-1             | 2024-07-19 05:42:32.935 UTC [1] LOG:  background worker "logical replication launcher" (PID 31) exited with exit code 1
2024-07-19 13:42:32 postgresql-1             | 2024-07-19 05:42:32.935 UTC [26] LOG:  shutting down
2024-07-19 13:42:33 postgresql-1             | 2024-07-19 05:42:33.075 UTC [26] LOG:  checkpoint starting: shutdown immediate
2024-07-19 13:42:34 postgresql-1             | 2024-07-19 05:42:34.653 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.370 s, sync=0.153 s, total=1.718 s; sync files=2, longest=0.078 s, average=0.077 s; distance=0 kB, estimate=0 kB; lsn=0/14E6C68, redo lsn=0/14E6C68
2024-07-19 13:42:34 postgresql-1             | 2024-07-19 05:42:34.657 UTC [1] LOG:  database system is shut down
2024-07-19 13:42:57 postgresql-1             | 
2024-07-19 13:42:57 postgresql-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-07-19 13:42:57 postgresql-1             | 
2024-07-19 13:22:31 cinnamon-1               | WARNING: PropertyNamingStrategy. is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies. instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.
2024-07-19 13:22:35 cinnamon-1               | Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'loritta' is required for type with serial name 'net.perfectdreams.loritta.morenitta.utils.config.BaseConfig', but it was missing
2024-07-19 13:22:35 cinnamon-1               |  at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
2024-07-19 13:22:35 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig.<init>(BaseConfig.kt:5)
2024-07-19 13:22:35 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:22:35 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:22:35 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeSerializableValue(Hocon.kt:176)
2024-07-19 13:22:35 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:63)
2024-07-19 13:22:35 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.LorittaLauncher.main(LorittaLauncher.kt:214)
2024-07-19 13:36:18 cinnamon-1               | WARNING: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent303825968926934417.jar)
2024-07-19 13:36:18 cinnamon-1               | WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
2024-07-19 13:36:18 cinnamon-1               | WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
2024-07-19 13:36:18 cinnamon-1               | WARNING: Dynamic loading of agents will be disallowed by default in a future release
2024-07-19 13:36:19 cinnamon-1               | Jul 19, 2024 5:36:19 AM com.fasterxml.jackson.databind.PropertyNamingStrategy$PropertyNamingStrategyBase <init>
2024-07-19 13:36:19 cinnamon-1               | WARNING: PropertyNamingStrategy. is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies. instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.
2024-07-19 13:36:19 cinnamon-1               | Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'loritta' is required for type with serial name 'net.perfectdreams.loritta.morenitta.utils.config.BaseConfig', but it was missing
2024-07-19 13:36:19 cinnamon-1               |  at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
2024-07-19 13:36:19 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig.<init>(BaseConfig.kt:5)
2024-07-19 13:36:19 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:36:19 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:36:19 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeSerializableValue(Hocon.kt:176)
2024-07-19 13:36:19 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:63)
2024-07-19 13:36:19 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.LorittaLauncher.main(LorittaLauncher.kt:214)
2024-07-19 13:41:22 cinnamon-1               | WARNING: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent914552688582894965.jar)
2024-07-19 13:41:22 cinnamon-1               | WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
2024-07-19 13:41:22 cinnamon-1               | WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
2024-07-19 13:41:22 cinnamon-1               | WARNING: Dynamic loading of agents will be disallowed by default in a future release
2024-07-19 13:41:23 cinnamon-1               | Jul 19, 2024 5:41:23 AM com.fasterxml.jackson.databind.PropertyNamingStrategy$PropertyNamingStrategyBase <init>
2024-07-19 13:41:23 cinnamon-1               | WARNING: PropertyNamingStrategy. is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies. instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.
2024-07-19 13:41:23 cinnamon-1               | Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'loritta' is required for type with serial name 'net.perfectdreams.loritta.morenitta.utils.config.BaseConfig', but it was missing
2024-07-19 13:41:23 cinnamon-1               |  at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
2024-07-19 13:41:23 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig.<init>(BaseConfig.kt:5)
2024-07-19 13:41:23 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:41:23 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:41:23 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeSerializableValue(Hocon.kt:176)
2024-07-19 13:41:23 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:63)
2024-07-19 13:41:23 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.LorittaLauncher.main(LorittaLauncher.kt:214)
2024-07-19 13:41:50 cinnamon-1               | WARNING: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent3988058340768886338.jar)
2024-07-19 13:41:50 cinnamon-1               | WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
2024-07-19 13:41:50 cinnamon-1               | WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
2024-07-19 13:41:50 cinnamon-1               | WARNING: Dynamic loading of agents will be disallowed by default in a future release
2024-07-19 13:41:52 cinnamon-1               | Jul 19, 2024 5:41:52 AM com.fasterxml.jackson.databind.PropertyNamingStrategy$PropertyNamingStrategyBase <init>
2024-07-19 13:41:52 cinnamon-1               | WARNING: PropertyNamingStrategy. is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies. instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.
2024-07-19 13:41:52 cinnamon-1               | Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'loritta' is required for type with serial name 'net.perfectdreams.loritta.morenitta.utils.config.BaseConfig', but it was missing
2024-07-19 13:41:52 cinnamon-1               |  at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
2024-07-19 13:41:52 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig.<init>(BaseConfig.kt:5)
2024-07-19 13:41:52 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:41:52 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:41:52 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeSerializableValue(Hocon.kt:176)
2024-07-19 13:41:52 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:63)
2024-07-19 13:41:52 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.LorittaLauncher.main(LorittaLauncher.kt:214)
2024-07-19 13:42:24 cinnamon-1               | WARNING: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent6175932339107575113.jar)
2024-07-19 13:42:24 cinnamon-1               | WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
2024-07-19 13:42:24 cinnamon-1               | WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
2024-07-19 13:42:24 cinnamon-1               | WARNING: Dynamic loading of agents will be disallowed by default in a future release
2024-07-19 13:42:25 cinnamon-1               | Jul 19, 2024 5:42:25 AM com.fasterxml.jackson.databind.PropertyNamingStrategy$PropertyNamingStrategyBase <init>
2024-07-19 13:42:25 cinnamon-1               | WARNING: PropertyNamingStrategy. is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies. instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.
2024-07-19 13:42:26 cinnamon-1               | Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'loritta' is required for type with serial name 'net.perfectdreams.loritta.morenitta.utils.config.BaseConfig', but it was missing
2024-07-19 13:42:26 cinnamon-1               |  at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
2024-07-19 13:42:26 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig.<init>(BaseConfig.kt:5)
2024-07-19 13:42:26 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:22:56 gabriela-image-server-1  | 05:22:56.432 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Creating Convolve Op...
2024-07-19 13:22:56 gabriela-image-server-1  | 05:22:56.598 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Finished Creating Op!
2024-07-19 13:23:06 gabriela-image-server-1  | 05:23:06.402 [DefaultDispatcher-worker-2] INFO ktor.application - Autoreload is disabled because the development mode is off.
2024-07-19 13:23:07 gabriela-image-server-1  | 05:23:07.014 [DefaultDispatcher-worker-2] INFO ktor.application - Application started in 0.97 seconds.
2024-07-19 13:23:07 gabriela-image-server-1  | 05:23:07.498 [DefaultDispatcher-worker-5] INFO ktor.application - Responding at http://0.0.0.0:8001
2024-07-19 13:36:25 gabriela-image-server-1  | 05:36:25.127 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Creating Convolve Op...
2024-07-19 13:36:25 gabriela-image-server-1  | 05:36:25.135 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Finished Creating Op!
2024-07-19 13:36:26 gabriela-image-server-1  | 05:36:26.968 [DefaultDispatcher-worker-1] INFO ktor.application - Autoreload is disabled because the development mode is off.
2024-07-19 13:36:27 gabriela-image-server-1  | 05:36:27.071 [DefaultDispatcher-worker-1] INFO ktor.application - Application started in 0.252 seconds.
2024-07-19 13:36:27 gabriela-image-server-1  | 05:36:27.121 [DefaultDispatcher-worker-2] INFO ktor.application - Responding at http://0.0.0.0:8001
2024-07-19 13:41:28 gabriela-image-server-1  | 05:41:27.998 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Creating Convolve Op...
2024-07-19 13:41:28 gabriela-image-server-1  | 05:41:28.002 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Finished Creating Op!
2024-07-19 13:41:29 gabriela-image-server-1  | 05:41:29.165 [DefaultDispatcher-worker-2] INFO ktor.application - Autoreload is disabled because the development mode is off.
2024-07-19 13:41:29 gabriela-image-server-1  | 05:41:29.228 [DefaultDispatcher-worker-2] INFO ktor.application - Application started in 0.149 seconds.
2024-07-19 13:41:29 gabriela-image-server-1  | 05:41:29.265 [DefaultDispatcher-worker-1] INFO ktor.application - Responding at http://0.0.0.0:8001
2024-07-19 13:42:26 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:42:26 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeSerializableValue(Hocon.kt:176)
2024-07-19 13:42:26 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:63)
2024-07-19 13:42:26 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.LorittaLauncher.main(LorittaLauncher.kt:214)
2024-07-19 13:42:58 postgresql-1             | 2024-07-19 05:42:58.065 UTC [1] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-07-19 13:42:58 postgresql-1             | 2024-07-19 05:42:58.065 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-19 13:42:58 postgresql-1             | 2024-07-19 05:42:58.065 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-07-19 13:42:58 postgresql-1             | 2024-07-19 05:42:58.255 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-19 13:42:58 postgresql-1             | 2024-07-19 05:42:58.523 UTC [29] LOG:  database system was shut down at 2024-07-19 05:42:34 UTC
2024-07-19 13:42:58 cinnamon-1               | WARNING: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent6787800206690238704.jar)
2024-07-19 13:42:58 cinnamon-1               | WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
2024-07-19 13:42:58 cinnamon-1               | WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
2024-07-19 13:42:58 cinnamon-1               | WARNING: Dynamic loading of agents will be disallowed by default in a future release
2024-07-19 13:42:58 postgresql-1             | 2024-07-19 05:42:58.633 UTC [1] LOG:  database system is ready to accept connections
2024-07-19 13:42:59 cinnamon-1               | Jul 19, 2024 5:42:59 AM com.fasterxml.jackson.databind.PropertyNamingStrategy$PropertyNamingStrategyBase <init>
2024-07-19 13:42:59 cinnamon-1               | WARNING: PropertyNamingStrategy. is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies. instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.
2024-07-19 13:42:59 cinnamon-1               | Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'loritta' is required for type with serial name 'net.perfectdreams.loritta.morenitta.utils.config.BaseConfig', but it was missing
2024-07-19 13:42:59 cinnamon-1               |  at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
2024-07-19 13:42:59 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig.<init>(BaseConfig.kt:5)
2024-07-19 13:42:59 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:42:59 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
2024-07-19 13:42:59 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeSerializableValue(Hocon.kt:176)
2024-07-19 13:42:59 cinnamon-1               |  at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:63)
2024-07-19 13:42:59 cinnamon-1               |  at net.perfectdreams.loritta.morenitta.LorittaLauncher.main(LorittaLauncher.kt:214)
2036-01-01 00:00:00 
2001-01-01 00:00:00 xited with code 1
gabriela-image-server-1  | 2024-07-19T05:43:09.346485599Z 05:43:09.338 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Creating Convolve Op...
2024-07-19 13:43:09 gabriela-image-server-1  | 05:43:09.347 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Finished Creating Op!
2024-07-19 13:43:11 gabriela-image-server-1  | 05:43:11.456 [DefaultDispatcher-worker-1] INFO ktor.application - Autoreload is disabled because the development mode is off.
2024-07-19 13:43:11 gabriela-image-server-1  | 05:43:11.532 [DefaultDispatcher-worker-1] INFO ktor.application - Application started in 0.15 seconds.
2024-07-19 13:43:11 gabriela-image-server-1  | 05:43:11.573 [DefaultDispatcher-worker-3] INFO ktor.application - Responding at http://0.0.0.0:8001

**Comment by MrPowerGamerBR** [comment]
You didn't follow all the instructions on the `SELF-HOSTING.md` because if you followed it you would know what was the issue.

> In the same folder as `docker-compose.yml` create an empty file named `loritta.conf`.

And again, we don't support self hosting Loritta, if you have any other issues, we aren't going to help.
