### ISSUE TITLE
My loritta.conf is empty after the build and it shows this error

### ISSUE THREAD

**Issue by 6despise** [LorittaBot/Loritta#2669]
PS D:\Repositories\Loritta> docker-compose up
time="2024-11-11T14:11:18+08:00" level=warning msg="D:\\Repositories\\Loritta\\docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
[+] Running 48/3
 ✔ cinnamon Pulled                                                                                                82.3s
 ✔ postgresql Pulled                                                                                              64.6s
 ✔ gabriela-image-server Pulled                                                                                   37.8s
[+] Running 4/4
 ✔ Network loritta_default                    Created                                                              0.1s
 ✔ Container loritta-gabriela-image-server-1  Created                                                              1.7s
 ✔ Container loritta-cinnamon-1               Created                                                              1.7s
 ✔ Container loritta-postgresql-1             Created                                                              1.7s
Attaching to cinnamon-1, gabriela-image-server-1, postgresql-1
postgresql-1             | The files belonging to this database system will be owned by user "postgres".
postgresql-1             | This user must also own the server process.
postgresql-1             |
postgresql-1             | The database cluster will be initialized with locale "en_US.utf8".
postgresql-1             | The default database encoding has accordingly been set to "UTF8".
postgresql-1             | The default text search configuration will be set to "english".
postgresql-1             |
postgresql-1             | Data page checksums are disabled.
postgresql-1             |
postgresql-1             | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgresql-1             | creating subdirectories ... ok
postgresql-1             | selecting dynamic shared memory implementation ... posix
postgresql-1             | selecting default max_connections ... 100
postgresql-1             | selecting default shared_buffers ... 128MB
postgresql-1             | selecting default time zone ... Etc/UTC
postgresql-1             | creating configuration files ... ok
postgresql-1             | running bootstrap script ... ok
postgresql-1             | performing post-bootstrap initialization ... ok
cinnamon-1               | WARNING: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent7160113297697793484.jar)
cinnamon-1               | WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
cinnamon-1               | WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
cinnamon-1               | WARNING: Dynamic loading of agents will be disallowed by default in a future release
postgresql-1             | initdb: warning: enabling "trust" authentication for local connections
postgresql-1             | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgresql-1             | syncing data to disk ... ok
postgresql-1             |
postgresql-1             |
postgresql-1             | Success. You can now start the database server using:
postgresql-1             |
postgresql-1             |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgresql-1             |
postgresql-1             | waiting for server to start....2024-11-11 06:12:44.725 UTC [48] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgresql-1             | 2024-11-11 06:12:44.732 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql-1             | 2024-11-11 06:12:44.746 UTC [51] LOG:  database system was shut down at 2024-11-11 06:12:44 UTC
postgresql-1             | 2024-11-11 06:12:44.752 UTC [48] LOG:  database system is ready to accept connections
postgresql-1             |  done
postgresql-1             | server started
postgresql-1             | CREATE DATABASE
postgresql-1             |
postgresql-1             |
postgresql-1             | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgresql-1             |
postgresql-1             | waiting for server to shut down....2024-11-11 06:12:44.978 UTC [48] LOG:  received fast shutdown request
postgresql-1             | 2024-11-11 06:12:44.982 UTC [48] LOG:  aborting any active transactions
postgresql-1             | 2024-11-11 06:12:44.983 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
postgresql-1             | 2024-11-11 06:12:44.984 UTC [49] LOG:  shutting down
postgresql-1             | 2024-11-11 06:12:44.987 UTC [49] LOG:  checkpoint starting: shutdown immediate
postgresql-1             | 2024-11-11 06:12:45.092 UTC [49] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.030 s, sync=0.061 s, total=0.108 s; sync files=301, longest=0.006 s, average=0.001 s; distance=4249 kB, estimate=4249 kB; lsn=0/190D0B0, redo lsn=0/190D0B0
cinnamon-1               | Nov 11, 2024 6:12:45 AM com.fasterxml.jackson.databind.PropertyNamingStrategy$PropertyNamingStrategyBase <init>
cinnamon-1               | WARNING: PropertyNamingStrategy. is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies. instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.
postgresql-1             | 2024-11-11 06:12:45.097 UTC [48] LOG:  database system is shut down
postgresql-1             |  done
postgresql-1             | server stopped
postgresql-1             |
postgresql-1             | PostgreSQL init process complete; ready for start up.
postgresql-1             |
cinnamon-1               | Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'loritta' is required for type with serial name 'net.perfectdreams.loritta.morenitta.utils.config.BaseConfig', but it was missing
cinnamon-1               |      at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
cinnamon-1               |      at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig.<init>(BaseConfig.kt:5)
cinnamon-1               |      at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
cinnamon-1               |      at net.perfectdreams.loritta.morenitta.utils.config.BaseConfig$$serializer.deserialize(BaseConfig.kt:5)
cinnamon-1               |      at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeSerializableValue(Hocon.kt:180)
cinnamon-1               |      at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:63)
cinnamon-1               |      at net.perfectdreams.loritta.morenitta.LorittaLauncher.main(LorittaLauncher.kt:200)
postgresql-1             | 2024-11-11 06:12:45.213 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgresql-1             | 2024-11-11 06:12:45.213 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql-1             | 2024-11-11 06:12:45.213 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresql-1             | 2024-11-11 06:12:45.220 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql-1             | 2024-11-11 06:12:45.230 UTC [64] LOG:  database system was shut down at 2024-11-11 06:12:45 UTC
postgresql-1             | 2024-11-11 06:12:45.236 UTC [1] LOG:  database system is ready to accept connections
cinnamon-1 exited with code 1
gabriela-image-server-1  | 06:12:48.532 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Creating Convolve Op...
gabriela-image-server-1  | 06:12:48.536 [main] INFO net.perfectdreams.gabrielaimageserver.generators.cortesflow.CortesFlowGenerator - Finished Creating Op!
gabriela-image-server-1  | 06:12:49.650 [DefaultDispatcher-worker-1] INFO ktor.application - Autoreload is disabled because the development mode is off.
gabriela-image-server-1  | 06:12:49.694 [DefaultDispatcher-worker-1] INFO ktor.application - Application started in 0.096 seconds.
gabriela-image-server-1  | 06:12:49.717 [DefaultDispatcher-worker-2] INFO ktor.application - Responding at http://0.0.0.0:8001

**Comment by MrPowerGamerBR** [comment]
Try deleting the `loritta.conf`, now that I'm thinking about it there shouldn't be a need to create a empty file because, if it exists, Loritta won't attempt to create a config file

**Comment by 6despise** [comment]
> Try deleting the `loritta.conf`, now that I'm thinking about it there shouldn't be a need to create a empty file because, if it exists, Loritta won't attempt to create a config file (that snippet should be removed from the docs)

thanks I will try this

**Comment by 6despise** [comment]
> Try deleting the `loritta.conf`, now that I'm thinking about it there shouldn't be a need to create a empty file because, if it exists, Loritta won't attempt to create a config file (that snippet should be removed from the docs)

When I tried this, it created a folder named loritta.conf without anything inside. FOLDER not a .CONF
so how to fix this
